#!/bin/sh
#PBS -l nodes=1:ppn=8
#PBS -l walltime=500:00:00
#PBS -l mem=44gb
#PBS -j oe
#PBS -m abe
#PBS -V
#PBS -M mljenior@umich.edu
#PBS -q first
#PBS -A schloss_lab

echo "ncpus-2.pbs"
cat $PBS_NODEFILE
qstat -f $PBS_JOBID

cd $PBS_O_WORKDIR

NCPUS=`wc -l $PBS_NODEFILE | awk '{print $1}'`


gunzip data/references/*.gz
bowtie2-build -f data/references/cdf.kegg.genes.fasta data/references/cdf_db
bowtie2-build -f data/references/cd630.select_genes.fasta data/references/cd630.select_genes_db


echo "qsub working directory absolute is"
echo $PBS_O_WORKDIR
exit
